# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Gu98bv_tbmq3Pel0SCaNe-4y6GlhZNT
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

x=[1,2,3,4,5,6,7,8]
y=[10,23,42,32,43,15,6,30]

print(x)
print(y)

plt.xlabel('XXX')
plt.ylabel('YYY')
plt.title('vungchung')
plt.plot(x,y)

plt.xlabel('XXX')
plt.ylabel('YYY')
plt.title('vungchung')
plt.plot(x,y,color='red')

plt.xlabel('XXX')
plt.ylabel('YYY')
plt.title('vungchung')
plt.plot(x,y, color='black', linewidth=5)

plt.xlabel('My course')
plt.ylabel('Marks')
plt.title('As a average Student')
plt.plot(x,y, color='blue',linewidth=2,marker='o', linestyle='dashdot')
# linestyle supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'

print("Tanzil")
A=[10,12,14]
B=[13,15,17]
x=int(input())
for n in range(x):
  n=n**2
  if n%2==0:
    A.append(n)
  else:
    B.append(n)

print(A)
print(B)

import matplotlib.pyplot as plt
plt.xlabel("A")
plt.ylabel("B")
plt.title("Vubgchung")
plt.plot(A,B, color="red",linewidth=2,marker="*")

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
x=[1,2,3,4]
y=[1,2,3,4]
plt.xlabel("X")
plt.ylabel("Y")
plt.title('Tanzil')
plt.plot(x,y, color='red')

import numpy as np
X=np.arange(-10,10,0.01)
x1=np.sin(X)
y1=np.cos(X)
plt.figure(figsize=(10,1) )

plt.plot(X,x1)
plt.plot(X,y1)
plt.legend(["sin","cos"])
plt.show()

plt.figure(figsize=(15,6))
plt.subplot(1,2,1)
plt.plot(X,x1)
plt.legend(["Sin"])
plt.subplot(1,2,2)
plt.plot(X,y1)
plt.legend(["cos"])
plt.savefig("test.pdf",transparent=True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Sample data
X = np.linspace(0, 10, 100)
x1 = np.sin(X)
y1 = np.cos(X)
data = np.random.randn(1000)  # Data for histogram and box plot

# Sin and Cos Line Plots
plt.figure(figsize=(15, 6))
plt.subplot(1, 2, 1)
plt.plot(X, x1)
plt.legend(["Sin"])
plt.title("Sine Curve")

plt.subplot(1, 2, 2)
plt.plot(X, y1)
plt.legend(["Cos"])
plt.title("Cosine Curve")
plt.savefig("test.pdf", transparent=True)
plt.show()

# Histogram Plot
plt.figure(figsize=(8, 4))
plt.hist(data, bins=30, color='skyblue', edgecolor='black')
plt.title("Histogram of Random Data")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

# Box Plot
plt.figure(figsize=(6, 4))
plt.boxplot(data, vert=True)
plt.title("Box Plot of Random Data")
plt.ylabel("Value")
plt.grid(True)
plt.show()

# Scatter Plot
plt.figure(figsize=(7, 5))
plt.scatter(X, x1, color='red', label='sin(x)')
plt.scatter(X, y1, color='blue', label='cos(x)', alpha=0.6)
plt.title("Scatter Plot of sin(x) and cos(x)")
plt.xlabel("X")
plt.ylabel("Value")
plt.legend()
plt.grid(True)
plt.show()

