# -*- coding: utf-8 -*-
"""python practice2 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSG5Zgajs-u75DblZrSt4fmtL4cmD-35
"""

print("""My name is kazi Tanzizul Haque.
I am a student of Aiub""")
print("Id",input())

A=[x**2 for x in range(10) if x%2==0]
print(A)

import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.arange(8)
c=np.arange(8).reshape(2,4)
print(A)
print(b)
print(c)
d=A[:3,1:3]
print(d)

Tan=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

#print(Tan[[0,1,2,3],[0,0,0,0]])
print()
print(np.array([Tan[0,0],Tan[1,0],Tan[2,0],Tan[3,0]]))
zil=np.array([0,0,0,0])
print(Tan[np.arange(4),zil])

x=np.full((3,3),7)
print(x)

y=np.random.random((3,3))
print(y)

x=np.array([1,2,3,4,5,6,222,343,5,23])
print(max(x))

z=np.array([[3,1,4,2],[12,3,4,52],[2,3,4,2]])

bool_index=(z>2)
print(bool_index)
print(z[bool_index])

a=np.array([[1,2],[3,4]], dtype=np.float64)
b=np.array([[2,3],[4,5]],dtype=np.int32)

print(np.add(a,b))

print(a+b)

a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

print(np.dot(a,b))

x=np.array([[2,3],[4,5]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x,axis=1))

print(np.mean(x))
print(np.mean(x, axis=1))
print()
print(x)
print()
print(x.T)

v=np.array([1,2,3])

print(v)
print(v.T)

"""# **Broadcasting**"""

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y=np.empty_like(x)

for i in range(4):
  y[ i, :]=x[i,:]+v
print(y)

